apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
  name: hello
spec:
  ports:
  - nodePort: 30001
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: hello
    tier: hello
  type: NodePort
